on: [push, pull_request]

name: Continuous integration

jobs:
  check:
    strategy:
      matrix:
        feature:
          [
            "arbitrary",
            "v3",
            "v3-paseto",
            "v3-paserk",
            "v3-id",
            "v3-pke",
            "v3-pbkw",
            "v3-wrap",
            "v3-local",
            "v3-public",
            "v4",
            "v4-paseto",
            "v4-paserk",
            "v4-id",
            "v4-pke",
            "v4-pbkw",
            "v4-wrap",
            "v4-local",
            "v4-public",
          ]
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo clippy --features ${{ matrix.feature }} -- -D warnings

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --all-features

  msrv:
    name: MSRV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.65.0
      - run: cargo check --all-features
